name: Test Coverage

on:
  push:
    branches:
      - "!production"
      - "!skipci*"
  pull_request:
    branches:
      - "!production"
      - "!skipci*"

jobs:
  coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      
      - name: Install dependencies
        shell: bash
        run: yarn install:all

      - name: Run tests with coverage
        shell: bash
        run: yarn coverage

      - name: Publish test coverage to Code Climate
        if: always() && env.CC_TEST_REPORTER_ID != ''
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage/clover.xml:clover
